"""MPDF Standard Stylesheet — Part of the MPDF v1.0 specification."""

MPDF_CSS = (
    "*{margin:0;padding:0;box-sizing:border-box}"
    "body{background:#f0f0f0;font-family:Georgia,'Times New Roman',Times,serif;"
    "font-size:16px;line-height:1.8;color:#1a1a1a;padding:40px 20px}"
    ".mpdf-document{max-width:800px;margin:0 auto}"
    ".mpdf-page{background:#fff;padding:60px 70px;margin-bottom:30px;"
    "box-shadow:0 2px 8px rgba(0,0,0,0.12);position:relative;"
    "min-height:900px;page-break-after:always}"
    ".mpdf-heading{font-family:Georgia,'Times New Roman',Times,serif;"
    "margin-bottom:0.6em;line-height:1.3}"
    "h1.mpdf-heading{font-size:28px;text-align:center;margin-bottom:0.8em}"
    "h2.mpdf-heading{font-size:22px;margin-top:1.2em}"
    "h3.mpdf-heading{font-size:18px;margin-top:1em}"
    ".mpdf-text{margin-bottom:1em;text-align:justify;hyphens:auto}"
    ".mpdf-gif,.mpdf-image{margin:1.5em auto;text-align:center}"
    ".mpdf-gif img,.mpdf-image img{max-width:100%;height:auto;"
    "border:1px solid #ddd;border-radius:3px}"
    ".mpdf-gif figcaption,.mpdf-image figcaption{font-size:13px;"
    "color:#666;margin-top:8px;font-style:italic}"
    ".mpdf-separator{border:none;border-top:1px solid #ccc;margin:2em 0}"
    "@media(max-width:600px){.mpdf-page{padding:30px 25px}"
    "h1.mpdf-heading{font-size:22px}body{padding:10px}}"
    "@media print{body{background:#fff;padding:0}"
    ".mpdf-page{box-shadow:none;padding:40px 50px;margin:0}"
    ".mpdf-gif img{max-height:400px}}"
    "@media(prefers-color-scheme:dark){body{background:#1e1e1e}"
    ".mpdf-page{background:#2d2d2d;color:#e0e0e0;"
    "box-shadow:0 2px 8px rgba(0,0,0,0.4)}"
    ".mpdf-gif img,.mpdf-image img{border-color:#444}"
    ".mpdf-gif figcaption,.mpdf-image figcaption{color:#999}"
    ".mpdf-separator{border-color:#444}}"
)
